site_name: b0nyo
theme:
  name: material
  palette:
    - scheme: slate # Usar slate como default suele ser mejor para el look "Dark"
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

nav:
  - Home: index.md
  - Machines:
    - Overview: machines/index.md
    - Hack The Box: machines/HTB/
  - Research: research/research.md
